name: 
on:
 push: 
  branches: [main]
jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Download a Build Artifact
     uses: actions/download-artifact@v8
     with:
    # Artifact name
      name: my-java-artifact
    # Destination path
      path: Javarepo1/target/*.jar
